# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.154.2+26.2

# Mod Properties
mod_version = 1.1.0
maven_group = io.wifi.bansaying
archives_base_name = MuteByCMD

loom_libraries_base=https://bmclapi2.bangbang93.com/maven/
loom_resources_base=https://bmclapi2.bangbang93.com/assets/

# Proxy
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=48889

# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=48889
# systemProp.https.nonProxyHosts=10.*|localhost